// Section Components
export { NavBar } from './nav-bar/NavBar'
export { Search } from './search/Search'
export { Hero } from './Hero'
export { LocationInfo } from './location-info/LocationInfo'
export { Holidays } from './holidays/Holidays'
export { BookingReasons } from './booking-reasons/BookingReasons'
export { Destinations } from './destinations/Destinations'
export { CustomerReviews } from './customer-reviews/CustomerReviews'
export { SignUp } from './SignUp'
export { QueryTest } from './query-test/QueryTest'
